### ISSUE TITLE
Consider error when a directory is input instead of a MOF

### ISSUE THREAD

**Issue by zjalexander** [Microsoft/DSCEA#45]
....Please don't ask how I stumbled into this situation, but if you put a directory path into -MofFile instead of a, um, ...file.... You get an error about Access Denied. Please throw a more descriptive error in this case, like "Path must be a file and not a directory". 

```
PS C:\demo> $mofDir = "C:\demo\DSCFromSCMJSON"
PS C:\demo> Start-DSCEAscan -MofFile $mofdir -computername LocalHost

WARNING: Access to the path 'C:\demo\DSCFromSCMJSON' is denied.
```

**Comment by rkyttle** [comment]
I feel like adding something like this to the beginning of the Start-DSCEAscan function should accomplish what you are asking

    if($MofFile -notlike '*.mof') {
        Write-Error "Please review your MofFile parameter, a full file path to a MOF file was not detected. Ex. -MofFile C:\Users\username\Documents\DSCEA\localhost.mof"
        return
    }
    else {    
    #Begin DSCEA Engine
    ..................................
    }

**Comment by rkyttle** [comment]
Adding Keith Hitchcock to get his thoughts

**Comment by rkyttle** [comment]
This should be resolved in the next release
