### ISSUE TITLE
Import-module DSCEA throws errors

### ISSUE THREAD

**Issue by majst32** [Microsoft/DSCEA#48]
When I try to import the module, I get an error importing Out-DataTable:
Unexpected token 'Â' in expression or statement.

It looks like there may be an extra character after some of the types that is being read as this invalid char.

**Comment by rkyttle** [comment]
Thanks Melissa!  I am able to repro.  I'll take a look at Out-DataTable to see what's going on.

In the meantime, you should be able to use the DSCEA module by just calling the functions, without a call to Import-Module DSCEA as PowerShell will import the functions automatically.

Thanks for calling this out!

**Comment by rkyttle** [comment]
It looks like some extra characters are getting added in somehow.  When I view the file on GitHub it looks fine, but after running (Install-Module DSCEA) and taking a look at the file on my file system, I see the extra characters which are causing the problem.

Possibly a copy paste issue with hidden characters, we will update this function on our next release and try to remove the characters to see if it resolves the issue
