### ISSUE TITLE
Error when you testing an incompatible server

### ISSUE THREAD

**Issue by ThierryBT** [Microsoft/DSCEA#58]
Hi Ralph and Keith and sorry for my Funny English.
When you check compliance, if all servers are not compatibles with Powershell version (see #57, New Powershell Check Version), you have an error message.

![dscea2](https://user-images.githubusercontent.com/28751337/26972049-35af9bc0-4d10-11e7-8c66-9817c7f3bf39.PNG)

Do you think it's possible to replace line 364 :
 Write-Progress -activity "Working..." -PercentComplete (($jobscomplete / $jobs.count)*100) -status "$([string]::Format("Time Elapsed: {0:d2}:{1:d2}:{2:d2}     Jobs Complete: {3} of {4} ", $elapsedTime.Elapsed.hours, $elapsedTime.Elapsed.minutes, $elapsedTime.Elapsed.seconds, $jobscomplete, $jobs.count))";

by

switch ($jobs.count)
{{$jobs.count -eq 0}{Write-host "Nothing to test ...";break}
{$jobs.count -ne 0}{Write-Progress -activity "Working..." -PercentComplete (($jobscomplete / $jobs.count)*100) -status "$([string]::Format("Time Elapsed: {0:d2}:{1:d2}:{2:d2}     Jobs Complete: {3} of {4} ", $elapsedTime.Elapsed.hours, $elapsedTime.Elapsed.minutes, $elapsedTime.Elapsed.seconds, $jobscomplete, $jobs.count))"}}

![dscea3](https://user-images.githubusercontent.com/28751337/26972063-47161cf4-4d10-11e7-95cd-2c1f829f8e41.png)

Regards
Thierry

**Comment by rkyttle** [comment]
Closing this issue, this will be resolved by implementing deeper checking to ensure that systems being scanned aren't just at WMF 5 or higher, but at the RTM version of WMF 5 or higher.
