### ISSUE TITLE
DSCEAScans

### ISSUE THREAD

**Issue by kinkster** [Microsoft/DSCEA#68]
I get this error when I have several hosts. 
Start-DSCEAscan -MofFile C:\w10localhost.mof -InputFile C:\output.txt -Force -OutputPath \\server\test\

It works for up to 200 hosts in output.txt and then after that I started to see these errors.  
Receive-Job : Cannot bind argument to parameter 'Job' because it is null.
At C:\Program Files\WindowsPowerShell\Modules\DSCEA\1.2.0.0\Functions\Start-DSCEAscan.ps1:322 char:37
+         $psjobresults = Receive-Job $psresults
+                                     ~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Receive-Job], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.ReceiveJobCommand
 
Attempted to divide by zero.
At C:\Program Files\WindowsPowerShell\Modules\DSCEA\1.2.0.0\Functions\Start-DSCEAscan.ps1:364 char:9
+         Write-Progress -activity "Working..." -PercentComplete (($job ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], RuntimeException
    + FullyQualifiedErrorId : RuntimeException

**Comment by kinkster** [comment]
The error happens here. It works without issue for 360 hosts but the next jump to 435 hosts consistently fails. I have played with -scantimeout set to 600 up to 12000 and jobtimeout from 10 up to 75

VERBOSE: DSCEA Scan has started
Receive-Job : Cannot bind argument to parameter 'Job' because it is null.
At C:\Program Files\WindowsPowerShell\Modules\DSCEA\1.2.0.0\Functions\Start-DSCEAscan.ps1:322 char:37
+         $psjobresults = Receive-Job $psresults
+                                     ~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Receive-Job], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.ReceiveJobCommand
 
VERBOSE: Connectivity testing complete

**Comment by rkyttle** [comment]
Are you using any custom resources in your configuration?  Can you provide how many items you are trying to scan?

**Comment by kinkster** [comment]
Hi Ralph

The actual MOF is quite basic. I am only using the service and registry resources. No custom resources.
9 services
3 registry

**Comment by kinkster** [comment]
This was done on a Win7 system. I have moved it to a 2012R2 server and seems to be consistent

**Comment by rkyttle** [comment]
You mentioned earlier, "The error happens here. It works without issue for 360 hosts but the next jump to 435 hosts consistently fails."

For the 75 systems that you are adding which brings things to 435, are you able to successfully perform a scan against those systems on their own?

**Comment by kinkster** [comment]
Yes, I could run against a much smaller number and have consistent successful scans.
I thought the issue was the amount of systems being scanned. It could still be, I was able to run against 422 hosts no problem.

**Comment by kinkster** [comment]
I moved script to 2012 R2 server. Seemed to work fine for close to 1000 hosts for 5 weeks. Now scan fails with no errors just a scan timeout. Number of hosts varies but around 400. What also is common is that Jobs complete: 398 of 400 (Two jobs are usually unfinished) is where it typically will hang and timeout. Threads go from 28 to 1482.

**Comment by kinkster** [comment]
So turns out those two jobs were issues with winrm. Previous to the scan I would do a test-wsman. This was not good enough. I had two hosts that would not allow me to winrm. I guess the -timeout option should have worked in this instance.
